remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Elixir Fortaleza Conf 2023]
description: [Uma conferência do ecossistema de Erlang, organizada por Elixir em Foco e ELUG-CE.]
